export const typographyClassNames = {
	h1: "scroll-m-20  text-foreground text-4xl font-extrabold tracking-tight text-balance mt-8 mb-4",
	h2: "scroll-m-20 text-foreground border-b pb-2 text-3xl font-semibold tracking-tight first:mt-0 mt-8 mb-3",
	h3: "scroll-m-20 text-2xl font-semibold tracking-tight mt-5 mb-2",
	h4: "scroll-m-20 text-xl font-semibold tracking-tight mt-6 mb-2",
	h5: "scroll-m-20 text-lg font-semibold tracking-tight mt-4 mb-2",
	h6: "scroll-m-20 text-base font-semibold tracking-tight mt-4 mb-2",
	p: "leading-7 [&:not(:first-child)]:mt-4",
	ol: "pl-6 list-decimal first:[&>li}:mt-3",
	ul: "pl-6 list-disc first:[&>li]:mt-3",
	blockquote: "mt-6 border-l-2 pl-6 italic",
	anchor: "text-blue-600 hover:underline hover:underline-offset-2",
	em: "italic tracking-tighter",
	strong: "font-bold",
	pre: "overflow-x-auto bg-muted/60 text-sm font-semibold leading-6 w-full pl-6 pr-4 py-3 mt-4 rounded-lg [&_code]:bg-transparent [&_code]:p-0",
	inlineCode:
		"relative rounded bg-muted/60 px-2 py-[0.2rem] font-code text-sm font-semibold ",
	subScript: "text-sm",
	superScript: "text-sm",
};
